### PR TITLE
Use AudioWorklet

### PR DESCRIPTION
**Pull request by Swimburger**
Instead of using recordrtc, use the built-in AudioWorklet to process the raw audio and send it to the real-time service.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_AudioWorklet

### CODE REVIEW

**Comment by vvabhiram** [comment]
Hi @Swimburger  .. Will this proposed change emit bytes in pcm format ? 

i am developing an extension in google chrome using manifest version 3. currently i am able to record the audio in webm format only. Once I start recording, every 10 seconds, i am capturing the blob that is recorded until that time using ondataavailable() event and sending the data to my fastapi backend server where i am converting the data to wav format using pydub and ffmpeg . the very first chunk is getting converted properly and the subsequent chunks are not getting converted due to header missing. I dont want to convert the audio in webm format in my backend. i want to capture the audio in pcm format in the browser extension itself. so, I tried using RecordRTC javascript library but i am getting this error : The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet) . 

so, will this proposed change of AudioWorkletNode emit pcm byte strings for every 100 ms of audio recording ?

**Comment by Swimburger** [comment]
@vvabhiram Yes, this is the only way to get PCM data from the microphone in the browser AFAIK.
This PR gets PCM data and buffers it until 100+ms then sends it to our real-time service.

**Review by MLawlz — APPROVED** [review]
This is awesome! Thank you @Swimburger 🙏🏻

**Comment by vvabhiram** [comment]
Hi @Swimburger  .. This solution works but the resultant audio file is containing 'tick tick' noise. Can you suggest me how to get rid of the noise ?

**Comment by Swimburger** [comment]
@vvabhiram I am not sure what you mean by that. There's noise present in the audio that's not coming from your microphone?

**Comment by vvabhiram** [comment]
Hii @Swimburger  .. Yes, there is some kind of distortion or noise in the audio file I generated in the backend. 

This is the link of sample audio file I hosted on my Google drive for you to listen to : [Audio with Noise](https://drive.google.com/file/d/1CDDSowkAitb_qcSVhQXiK7Nez7cG6grP/view?usp=drive_link) . 

I am trying to get rid of the noise as I intended to use this audio for playback and better user experience. I tried every LLM in the market for help and they are clueless about the issue. 

I am using the audio converter code in this pull request to record the audio in PCM format and transmitting it over websocket.

```
stream = await navigator.mediaDevices.getUserMedia({
        audio: {
          mandatory: {
            chromeMediaSource: 'tab',
            chromeMediaSourceId: streamId
          }
        }
      });

      audioContext = new AudioContext({
        sampleRate:16_000,
        latencyHint: 'balanced'
      })
      
      source = audioContext.createMediaStreamSource(stream)
      await audioContext.audioWorklet.addModule('audio-processor.js');
      audioWorkletNode = new AudioWorkletNode(audioContext, 'audio-processor');
  
      source.connect(audioWorkletNode);
      audioWorkletNode.connect(audioContext.destination);

      audioWorkletNode.port.onmessage = (event) => {
        const currentBuffer = new Int16Array(event.data.audio_data);
        audioBufferQueue = mergeBuffers(
          audioBufferQueue,
          currentBuffer
        );
  
        const bufferDuration =
          (audioBufferQueue.length / audioContext.sampleRate) * 1000;
  
        // wait until we have 100ms of audio data
        if (bufferDuration >= 100) {
          const totalSamples = Math.floor(audioContext.sampleRate * 0.1);
  
          const finalBuffer = new Uint8Array(
            audioBufferQueue.subarray(0, totalSamples).buffer
          );
  
          audioBufferQueue = audioBufferQueue.subarray(totalSamples)
          const b64Encoded = btoa(String.fromCharCode.apply(null,finalBuffer))

          const message = {
            event : 'media',
            data : b64Encoded
          }
          const payload = JSON.stringify(message)

          if(streamSocket.readyState == WebSocket.OPEN){

            if(tempPayload.buffer.length > 0){
              tempPayload.data = tempPayload.buffer.join('')
              const req = {event:tempPayload.event,data:tempPayload.data}
              sendLogs(`${tabId} @ ${new Date().toLocaleString()} : [SOCKET SEND] Sending Buffer data when Websocket is Ready`)
              streamSocket.send(JSON.stringify(req))
              tempPayload.buffer = []
              tempPayload.data = null
            }
            streamSocket.send(payload)
```


While recording the audio in browser, I am sending it as chunks in real time over websocket to my FastAPI backend server written in Python. 

```
@router.websocket("/upload/{stream_id}")
async def socket_stream(sockets:WebSocket,stream_id:str=Path(...)):
    await sockets.accept()
    count = 0
    try:
        is_stream_open = True
        wav_file = os.path.join('output_files',f'{stream_id}_audio.wav')
        print(f'Websocket started listening on {stream_id} . Client state : {sockets.application_state}')

        with wave.open(f=wav_file,mode='wb') as wav:
            wav.setnchannels(1)
            wav.setsampwidth(2)  # 16-bit audio
            wav.setframerate(16000)
            buffer = np.array([],dtype=np.int16)
            
            while is_stream_open:
                data = await sockets.receive_json()
                if data['event'] == 'media' and data['data']:
                    count += 1
                    decoded_data = base64.b64decode(data['data'])
                    audio_chunk = np.frombuffer(decoded_data,dtype=np.int16)
                    buffer = np.concatenate((buffer,audio_chunk))

                    while len(buffer) >= 1600:
                        chunk = buffer[:1600]
                        buffer = buffer[1600:]
                        wav.writeframes(chunk.tobytes())
               elif data['event'] == 'close':
                    print(f'Recording Stopped')
                    detector.stream_ended = True
                    #await detector.stop_transcribing()
                    break
                else:
                    print('Data not received from Socket')
```

This is how I am accumulating the audio in wav files. You seem to be a subject expert on this. Kindly help me in resolving this issue.

**Comment by vvabhiram** [comment]
Hi @Swimburger,
I discovered that the noise was due to the small buffer size of 100ms chunks. After increasing the buffer chunk size to 1 second, the noise disappeared. Thank you for providing this AudioWorklet processor. Without it, I wouldn't have been able to convert audio to PCM in real time.

**Comment by Swimburger** [comment]
Interesting, I had no idea what was causing it. I'm glad you found a solution.

**Pull request merged**
